### ISSUE TITLE
关于项目稳定性和安全性的考量

### ISSUE THREAD

**Issue by xuzhenhao** [madaoCN/FxxkBaseClass-MVVM-ReactCocoa#2]
AOP的思路很好。但是在实际落地的正式项目中，还是有些踌躇。比如Aspects和JSPatch就有很知名的冲突问题。再加上平时项目中会使用各种开源非开源的库，hook总感觉不是一条好的路。请问你有什么好的建议吗？感谢

**Comment by madaoCN** [comment]
非常不建议在实际项目中使用AOP, 虽然写起来很爽，但是定位排查问题比较困难，还是使用传统的继承来稳妥，此项目就当一种思路看看就行了
